name: Deploy Site with updated data

on: 
    push: 
        branches: 
            - main
    schedule:
        - cron:  '49 12 * * 1'
    workflow_dispatch:

jobs: 
    build:
        name: Fetch data and build
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout
                uses: actions/checkout@v4

            -   name: "Checkout SGGAP"
                uses: actions/checkout@v4
                with: 
                    path: sggap
                    repository: twilcynder/startgg-api-programs
            -   name: "Checkout TLSEvents"
                uses: actions/checkout@v4
                with:
                    repository: twilcynder/tlsEvents
                    token: ${{ secrets.PAT }}
            -   name: Install Node
                uses: actions/setup-node@v4
            -   name: Setup dependencies
                run: |
                    cd sggap
                    npm Install
                    mv node_modules ..
                    cd ..
                    ls -l
                    node calc.js
            -   name: Upload artifact
                uses: actions/upload-pages-artifact@v3
    deploy:
        name: Deploy Sites
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        runs-on: ubuntu-latest
        needs: build
        permissions:
            pages: write
            id-token: write
        steps:
            -   name: Deploy to GitHub Pages
                id: deployment
                uses: actions/deploy-pages@v4        